language: c
sudo: required
dist: focal

addons:
  apt:
    update: true

before_install:
 - sudo apt install -y fastd

script:
 - ./.verify.sh
 - ./.check.py

notifications:
  email:
    recipients:
      - keys@freifunk-mwu.de
    on_success: always
    on_failure: always
  irc:
    channels:
      - "ircs://irc.hackint.org:6697/#ffmwu-feed"
    template:
      - "%{repository_slug} (%{branch} - %{commit}): %{message}"
      - "Build details : %{build_url}"
    on_success: always
    on_failure: always

